version: "3.9"  # optional since v1.27.0

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userDB
      MYSQL_USER: mysql
      MYSQL_PASSWORD: secret
    ports:
      - '3306:3306'
    networks:
      - local-user
    volumes:
      - db:/var/lib/mysql-users/data


networks:
  local-user:

volumes:
  db: